#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

# CustomWindowRules
bspc rule -a yesplaymusic state=floating

# AutoStart
feh --bg-fill ~/WallPapers/20230822_211207.jpg &
# ibus-daemon -drx
fcitx -d
numlockx on
picom -b  --config ~/.config/picom/picom.conf &
# bash ~/.config/polybar/launch.sh --shades
bash -C ~/.config/polybar/launch.sh
